# Generated by Django 2.0 on 2018-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('professeur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='devoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDevoir', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('pathSujet', models.CharField(max_length=100)),
                ('pathCorrection', models.CharField(max_length=100)),
                ('pathEntrees', models.CharField(max_length=100)),
                ('idProfesseur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='realisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEtudiant', models.CharField(max_length=100)),
                ('emailEtudiant', models.CharField(max_length=100)),
                ('idDevoir', models.CharField(max_length=100)),
            ],
        ),
    ]
