# Generated by Django 2.0 on 2018-01-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='idClasse',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
