# Generated by Django 2.0 on 2018-01-25 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEtudiant', models.CharField(default='', max_length=100)),
                ('idClasse', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEtudiant', models.CharField(default='', max_length=100)),
                ('idDevoir', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='devoir',
            name='consignes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='devoir',
            name='dateDebut',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AddField(
            model_name='devoir',
            name='dateFin',
            field=models.CharField(default='00/00/0000', max_length=10),
        ),
        migrations.AddField(
            model_name='devoir',
            name='idClasse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='realisation',
            name='note',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='reponse',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='pathCorrection',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='pathEntrees',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='emailEtudiant',
            field=models.EmailField(max_length=100),
        ),
    ]
