# Generated by Django 2.0 on 2018-01-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0002_devoir_idclasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='dateDebut',
            field=models.CharField(default='00/00/0000', max_length=100),
        ),
        migrations.AddField(
            model_name='devoir',
            name='dateFin',
            field=models.CharField(default='00/00/0000', max_length=100),
        ),
    ]
