# Generated by Django 2.0 on 2018-01-19 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0003_auto_20180119_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='dateDebut',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='dateFin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='idClasse',
            field=models.CharField(default='', max_length=100),
        ),
    ]
