# Generated by Django 2.0 on 2018-01-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0004_auto_20180119_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='dateFin',
            field=models.CharField(default='00/00/0000', max_length=10),
        ),
    ]
