# Generated by Django 2.0 on 2018-03-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0005_auto_20180119_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEtudiant', models.CharField(max_length=100)),
                ('idClasse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEtudiant', models.CharField(max_length=100)),
                ('idDevoir', models.CharField(max_length=100)),
            ],
        ),
    ]
