# Generated by Django 2.0 on 2018-01-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0006_appartient_participe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartient',
            name='idClasse',
        ),
        migrations.RemoveField(
            model_name='appartient',
            name='idEtudiant',
        ),
        migrations.RemoveField(
            model_name='participe',
            name='idDevoir',
        ),
        migrations.RemoveField(
            model_name='participe',
            name='idEtudiant',
        ),
    ]
