# Generated by Django 2.0 on 2018-01-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0007_auto_20180122_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartient',
            name='idClasse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appartient',
            name='idEtudiant',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participe',
            name='idDevoir',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participe',
            name='idEtudiant',
            field=models.CharField(default='', max_length=100),
        ),
    ]
