# Generated by Django 2.0 on 2018-01-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0008_auto_20180122_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='consignes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
